site_name: Documentacion - Facelad

theme: minty

extra:
  favicon: "img/favicon.ico"
  logo: "img/logo.png"

nav:
  - Home: index.md
  # - About: about.md
  - ¿Que es un hosting?: hosting.md
  - ¿Que es un dominio?: domain.md
